# to convert a string in lowercase we use lower function
a="NDKNOE"
print(a.lower())

str = input('enter your name :').lower()
print(str)


# SWAP UPPPER TITLE(SENTENCE  JITNE BHI WORDS ONKE FIRST LETTER CAPITAL)

# SEARCHING AND REPLACING (FIND)

# MODIFY NAHI KAR SAKTE BUT VALUE TO REPLACE KAR SAKTE HAI

# SPLITTING AND JOINING
# SPLIT METHOD BREAKS THE STRING BASED ON A DELIMETER SPLIT METHOD RETURNS A LIST AFTER BREAKING THE STRING INTO NEW INDIVIDUAL STRING

# CHECKING METHODS
# STARTSWITH ISALNUM